version: '3.8'
services:
  redis:
    image: redis:7-alpine
    networks:
      - broker-rabbit
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    image: rabbitmq:3-management    # Версия с включенной панелью управления
    container_name: rabbitmq
    ports:
      - "5672:5672"                 # Порт для взаимодействия с приложениями (AMQP)
      - "15672:15672"               # Порт для доступа к веб-интерфейсу управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - broker-rabbit

networks:
  broker-rabbit:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data: